#***********************************************************************#
#*                                                                     *#
#*   AUTHOR:  BH4DGT                                                   *#
#*   DATE:    2020/4/28                                                *#
#*   PURPOSE: This file contains the makefile rules for building the   *#
#*            library                                                  *#
#*                                                                     *#
#***********************************************************************#

SUBDIRS	=
OBJS    = sim900.o
OBJS   += sim900.o
OBJS   += sim900.o

include $(SYS_BASE)\rules\rules.libary

