#***********************************************************************#
#*                                                                     *#
#*   AUTHOR:  BH4DGT                                                   *#
#*   DATE:    2020/4/28                                                *#
#*   PURPOSE: This file contains the makefile rules for building the   *#
#*            library                                                  *#
#*                                                                     *#
#***********************************************************************#

SUBDIRS	= Simcom

OBJS    = 

include $(SYS_BASE)\rules\rules.libary